import { useState } from 'react';
import { Pencil, Plus, Archive, RotateCcw } from 'lucide-react';
import { money, type Restaurant } from '../lib/api';
import { ConfirmDialog, EmptyBlock, EntityDialog, SectionHeading, type Field, type Write, number } from './admin-ui';

const fields: Field[] = [
  { key:'name', label:'اسم المطعم', required:true }, { key:'phone', label:'رقم الهاتف', type:'tel', required:true },
  { key:'address', label:'العنوان', required:true }, { key:'deliveryFee', label:'رسوم التوصيل (ر.س)', type:'number', min:0, step:'0.01' },
  { key:'description', label:'وصف المطعم', type:'textarea' },
];
export default function AdminRestaurants({ restaurants, write }: { restaurants: Restaurant[]; write: Write }) {
  const [editing, setEditing] = useState<Restaurant | 'new' | null>(null);
  const [archiving, setArchiving] = useState<Restaurant | null>(null);
  const [restoring, setRestoring] = useState<Restaurant | null>(null);
  return <div className="admin-workspace"><SectionHeading title="المطاعم" subtitle={`${money(restaurants.length)} مطعم مدرج · إدارة بيانات المطاعم وحالة ظهورها`}><button className="admin-action primary" onClick={() => setEditing('new')} data-testid="button-add-restaurant"><Plus size={16}/>إضافة مطعم</button></SectionHeading><div className="admin-card">{restaurants.length ? <div className="admin-table-scroll"><table className="admin-table"><thead><tr><th>المطعم</th><th>التواصل</th><th>العنوان</th><th>رسوم التوصيل</th><th>الحالة</th><th>الإجراءات</th></tr></thead><tbody>{restaurants.map(r => <tr key={r.id} data-testid={`row-restaurant-${r.id}`}><td><strong>{r.name}</strong><small dir="ltr">#{r.id}</small></td><td dir="ltr">{r.phone || '—'}</td><td>{r.address || '—'}</td><td>{money(r.deliveryFee)} ر.س</td><td><span className="status-pill">{r.status === 'ARCHIVED' ? 'مؤرشف' : r.status === 'INACTIVE' ? 'غير نشط' : 'مدرج'}</span></td><td><div className="admin-actions"><button className="admin-action" onClick={() => setEditing(r)} data-testid={`button-edit-restaurant-${r.id}`}><Pencil size={14}/>تعديل</button>{r.status === 'ARCHIVED' ? <button className="admin-action" onClick={() => setRestoring(r)} data-testid={`button-restore-restaurant-${r.id}`}><RotateCcw size={14}/>استعادة</button> : <button className="admin-action danger" onClick={() => setArchiving(r)} data-testid={`button-archive-restaurant-${r.id}`}><Archive size={14}/>أرشفة</button>}</div></td></tr>)}</tbody></table></div> : <EmptyBlock title="لا توجد مطاعم" text="أضف أول مطعم لبدء إدارة القوائم والطلبات."/>}</div>
  <EntityDialog open={!!editing} onClose={() => setEditing(null)} title={editing === 'new' ? 'إضافة مطعم' : 'تعديل بيانات المطعم'} fields={fields} initial={editing === 'new' ? {} : editing || {}} testId="restaurant" onSave={async values => { const name = String(values.name).trim(), phone = String(values.phone).trim(), address = String(values.address).trim(); if (!name || !phone || !address) throw new Error('اسم المطعم ورقم الهاتف والعنوان حقول مطلوبة ولا يمكن تركها فارغة.'); const body = { name, phone, address, description:values.description || null, deliveryFee:number(values.deliveryFee) }; if (editing === 'new') await write('/api/admin/restaurants','POST',body); else if (editing) await write(`/api/admin/restaurants/${editing.id}`,'PATCH',body); }}/>
  <ConfirmDialog open={!!archiving} onClose={() => setArchiving(null)} title="أرشفة المطعم؟" description={`سيُخفى ${archiving?.name || 'المطعم'} من القائمة دون حذف سجل الطلبات السابق.`} action="أرشفة المطعم" testId="restaurant" onConfirm={async () => { if (archiving) await write(`/api/admin/restaurants/${archiving.id}`,'DELETE'); }}/>
  <ConfirmDialog open={!!restoring} onClose={() => setRestoring(null)} title="استعادة المطعم؟" description={`سيُعاد تفعيل ${restoring?.name || 'المطعم'} ويصبح متاحاً في القائمة مجدداً.`} action="تأكيد الاستعادة" testId="restaurant-restore" onConfirm={async () => { if (restoring) await write(`/api/admin/restaurants/${restoring.id}`,'PATCH',{status:'ACTIVE'}); }}/>
  </div>;
}