import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { api, money, type StatsData } from '../lib/api';
import { EmptyBlock, SectionError, SectionHeading, SectionLoading } from './admin-ui';

type Period = { period:string; orders:number; orderValue:number };
type Ranked = { name:string; orders:number; orderValue:number };
export default function AdminAnalytics({ token }: { token: string }) {
  const [period, setPeriod] = useState('day');
  const [from, setFrom] = useState('');
  const [to, setTo] = useState('');
  const [metric, setMetric] = useState<'orders' | 'orderValue'>('orders');
  const stats = useQuery({ queryKey:['admin','stats','filtered',token,period,from,to], queryFn:() => api.adminStats(token,{period,from,to}), enabled:!!token, retry:1 });
  const raw:StatsData = stats.data || {};
  const summary = (raw.summary || {}) as Record<string,unknown>;
  const periods = Array.isArray(raw.periods) ? raw.periods as Period[] : [];
  const ranked = Array.isArray(raw.byRestaurant) ? raw.byRestaurant as Ranked[] : [];
  const scope = `${from || 'بداية البيانات'} — ${to || 'اليوم'} · تجميع ${period === 'day' ? 'يومي' : period === 'week' ? 'أسبوعي' : 'شهري'}`;
  return <div className="admin-workspace"><SectionHeading title="التحليلات" subtitle="إحصاءات الخادم الفعلية، وليست عينة الطلبات المعروضة"/>
    <div className="admin-card admin-card-pad admin-filter"><label>التجميع <select className="admin-input" value={period} onChange={e => setPeriod(e.target.value)} data-testid="select-stats-period"><option value="day">يومي</option><option value="week">أسبوعي</option><option value="month">شهري</option></select></label><label>من <input className="admin-input" type="date" value={from} max={to || undefined} onChange={e => setFrom(e.target.value)} data-testid="input-stats-from"/></label><label>إلى <input className="admin-input" type="date" value={to} min={from || undefined} onChange={e => setTo(e.target.value)} data-testid="input-stats-to"/></label><button className="admin-action" onClick={() => { setFrom('');setTo('');setPeriod('day'); }} data-testid="button-reset-stats-filters">إعادة الضبط</button></div>
    {stats.isLoading ? <SectionLoading/> : stats.error ? <SectionError error={stats.error} retry={() => { void stats.refetch(); }}/> : <>
      <p className="subtle text-sm" data-testid="text-stats-scope">نطاق البيانات: {scope}</p>
      <div className="metric-grid"><div className="metric"><span className="metric-label">إجمالي الطلبات</span><strong data-testid="text-analytics-orders">{summary.totalOrders == null ? '—' : money(Number(summary.totalOrders))}</strong><span className="metric-note">حسب الفترة المحددة</span></div><div className="metric"><span className="metric-label">قيمة الطلبات</span><strong data-testid="text-analytics-value">{summary.totalOrderValue == null ? '—' : `${money(Number(summary.totalOrderValue))} ر.س`}</strong><span className="metric-note">إجمالي القيمة للفترة</span></div></div>
      <div className="admin-card"><div className="admin-card-pad flex items-center justify-between gap-3 flex-wrap"><div><h3 className="font-extrabold">اتجاه الأداء</h3><p className="subtle text-xs mt-1">{scope}</p></div><div className="admin-tabs"><button aria-pressed={metric === 'orders'} onClick={() => setMetric('orders')} data-testid="button-chart-orders">الطلبات</button><button aria-pressed={metric === 'orderValue'} onClick={() => setMetric('orderValue')} data-testid="button-chart-value">القيمة</button></div></div>{periods.length ? <div className="admin-chart" role="img" aria-label={`منحنى ${metric === 'orders' ? 'عدد الطلبات' : 'قيمة الطلبات'} للفترة المحددة`}><ResponsiveContainer width="100%" height="100%"><AreaChart data={periods} margin={{top:12,right:10,left:8,bottom:8}}><CartesianGrid stroke="#e9edf5" strokeDasharray="3 3" vertical={false}/><XAxis dataKey="period" tick={{fontSize:11,fill:'#8390a4'}}/><YAxis tick={{fontSize:11,fill:'#8390a4'}} width={50} allowDecimals={metric !== 'orders'}/><Tooltip contentStyle={{direction:'rtl',borderRadius:12,border:'1px solid #e1e7f0'}} formatter={v => [metric === 'orders' ? `${money(Number(v))} طلب` : `${money(Number(v))} ر.س`,metric === 'orders' ? 'الطلبات' : 'القيمة']}/><Area type="monotone" dataKey={metric} stroke="#6263dc" fill="#e8e9ff" strokeWidth={3} isAnimationActive={false}/></AreaChart></ResponsiveContainer></div> : <EmptyBlock title="لا توجد نقاط زمنية" text="لم يُرجع الخادم بيانات للفترة المحددة."/>}</div>
      <div className="admin-card"><div className="admin-card-pad"><h3 className="font-extrabold">التوزيع الزمني</h3><p className="subtle text-xs mt-1">{scope}</p></div>{periods.length ? <div className="admin-table-scroll"><table className="admin-table"><thead><tr><th>الفترة</th><th>الطلبات</th><th>القيمة</th></tr></thead><tbody>{periods.map((p,i) => <tr key={`${p.period}-${i}`} data-testid={`row-stats-period-${i}`}><td>{p.period}</td><td>{money(p.orders)}</td><td>{money(p.orderValue)} ر.س</td></tr>)}</tbody></table></div> : <EmptyBlock title="لا سجلات" text="جرّب نطاقاً زمنياً آخر."/>}</div>
      <div className="admin-card"><div className="admin-card-pad"><h3 className="font-extrabold">الأداء حسب المطعم</h3><p className="subtle text-xs mt-1">{scope}</p></div>{ranked.length ? <div className="admin-table-scroll"><table className="admin-table"><thead><tr><th>المطعم</th><th>الطلبات</th><th>القيمة</th></tr></thead><tbody>{ranked.map((r,i) => <tr key={`${r.name}-${i}`} data-testid={`row-stats-restaurant-${i}`}><td><strong>{r.name}</strong></td><td>{money(r.orders)}</td><td>{money(r.orderValue)} ر.س</td></tr>)}</tbody></table></div> : <EmptyBlock title="لا مطاعم في هذه الفترة" text="تظهر المطاعم بعد تسجيل الطلبات في النطاق المحدد."/>}</div>
    </>}</div>;
}