import { useEffect, useState } from 'react';
import { Archive, Pencil, Plus, RotateCcw, Tags, Utensils } from 'lucide-react';
import { money, type Restaurant } from '../lib/api';
import { useAdminMenu, type AdminCategory, type AdminProduct } from '../hooks/use-admin';
import { ConfirmDialog, EmptyBlock, EntityDialog, SectionError, SectionHeading, SectionLoading, type Field, type Write, number, text } from './admin-ui';

export default function AdminMenuPage({ restaurants, token, write }: { restaurants: Restaurant[]; token: string; write: Write }) {
  const [restaurantId, setRestaurantId] = useState<number | null>(restaurants[0]?.id ?? null);
  useEffect(() => { if (!restaurants.some(r => r.id === restaurantId)) setRestaurantId(restaurants[0]?.id ?? null); }, [restaurants, restaurantId]);
  const menu = useAdminMenu(token, restaurantId);
  const [category, setCategory] = useState<AdminCategory | 'new' | null>(null);
  const [product, setProduct] = useState<AdminProduct | 'new' | null>(null);
  const [remove, setRemove] = useState<{ type: 'category' | 'product'; id: number; name: string } | null>(null);
  const [restore, setRestore] = useState<AdminCategory | null>(null);
  const categories = menu.data?.categories || [];
  const activeCategories = categories.filter(c => c.isAvailable !== false);
  const products = menu.data?.products || [];
  const productFields: Field[] = [
    { key:'name', label:'اسم الصنف', required:true }, { key:'categoryId', label:'التصنيف', type:'select', required:true, options:activeCategories.map(c => ({ value:String(c.id), label:c.name })) },
    { key:'price', label:'السعر (ر.س)', type:'number', required:true, min:0, step:'0.01' }, { key:'stockQuantity', label:'الكمية المتاحة', type:'number', min:0, step:'1' },
    { key:'imageUrl', label:'رابط الصورة' }, { key:'isAvailable', label:'متاح للطلب', type:'checkbox' }, { key:'description', label:'الوصف', type:'textarea' },
  ];
  return <div className="admin-workspace"><SectionHeading title="قائمة الطعام" subtitle="التصنيفات والأصناف المعروضة للزبائن، لكل مطعم على حدة"><button className="admin-action" disabled={!restaurantId} onClick={() => setCategory('new')} data-testid="button-add-category"><Plus size={15}/>تصنيف جديد</button><button className="admin-action primary" disabled={!restaurantId || !activeCategories.length} onClick={() => setProduct('new')} data-testid="button-add-product" title={!activeCategories.length ? 'أضف تصنيفاً أو استعد تصنيفاً مؤرشفاً أولاً' : undefined}><Plus size={15}/>صنف جديد</button></SectionHeading>
  <div className="admin-filter"><label htmlFor="admin-menu-restaurant">المطعم الحالي</label><select id="admin-menu-restaurant" className="admin-input" value={restaurantId ?? ''} onChange={e => setRestaurantId(Number(e.target.value))} data-testid="select-menu-restaurant">{restaurants.map(r => <option key={r.id} value={r.id}>{r.name}</option>)}</select></div>
  {!restaurantId ? <div className="admin-card"><EmptyBlock title="ابدأ بإضافة مطعم" text="تحتاج القائمة إلى مطعم قبل إضافة التصنيفات والأصناف."/></div> : menu.isLoading ? <SectionLoading/> : menu.error ? <SectionError error={menu.error} retry={() => { void menu.refetch(); }}/> : <>
  {!activeCategories.length && <div className="notice">أضف تصنيفاً أو استعد تصنيفاً مؤرشفاً أولاً؛ كل صنف يجب أن يرتبط بتصنيف متاح.</div>}
  <div className="admin-card"><div className="admin-card-pad flex items-center gap-2 border-b border-slate-100"><Tags size={19} color="#6263dc"/><h3 className="font-bold">التصنيفات · {money(categories.length)}</h3></div>{categories.length ? <div className="admin-table-scroll"><table className="admin-table"><thead><tr><th>التصنيف</th><th>الأصناف المرتبطة</th><th>الحالة</th><th>الإجراءات</th></tr></thead><tbody>{categories.map(c => <tr key={c.id} data-testid={`row-category-${c.id}`}><td><strong>{c.name}</strong></td><td>{money(products.filter(p => p.categoryId === c.id).length)}</td><td><span className="status-pill" data-testid={`status-category-${c.id}`}>{c.isAvailable === false ? 'مؤرشف' : 'متاح'}</span></td><td><div className="admin-actions"><button className="admin-action" onClick={() => setCategory(c)} data-testid={`button-edit-category-${c.id}`}><Pencil size={14}/>تعديل</button>{c.isAvailable === false ? <button className="admin-action" onClick={() => setRestore(c)} data-testid={`button-restore-category-${c.id}`}><RotateCcw size={14}/>استعادة</button> : <button className="admin-action danger" onClick={() => setRemove({ type:'category', id:c.id, name:c.name })} data-testid={`button-delete-category-${c.id}`}><Archive size={14}/>أرشفة</button>}</div></td></tr>)}</tbody></table></div> : <EmptyBlock title="لا تصنيفات بعد" text="أنشئ تصنيفاً لتنظيم قائمة المطعم."/>}</div>
  <div className="admin-card"><div className="admin-card-pad flex items-center gap-2 border-b border-slate-100"><Utensils size={19} color="#6263dc"/><h3 className="font-bold">الأصناف · {money(products.length)}</h3></div>{products.length ? <div className="admin-table-scroll"><table className="admin-table"><thead><tr><th>الصنف</th><th>التصنيف</th><th>السعر</th><th>التوفر</th><th>الإجراءات</th></tr></thead><tbody>{products.map(p => <tr key={p.id} data-testid={`row-product-${p.id}`}><td><strong>{p.name}</strong><small>{p.description || 'بدون وصف'}</small></td><td>{categories.find(c => c.id === p.categoryId)?.name || p.category || 'بدون تصنيف'}</td><td>{money(p.price)} ر.س</td><td><span className="status-pill">{p.isAvailable === false ? 'غير متاح' : 'متاح'}</span></td><td><div className="admin-actions"><button className="admin-action" onClick={() => setProduct(p)} data-testid={`button-edit-product-${p.id}`}><Pencil size={14}/>تعديل</button><button className="admin-action danger" onClick={() => setRemove({ type:'product', id:p.id, name:p.name })} data-testid={`button-remove-product-${p.id}`}><Archive size={14}/>إزالة</button></div></td></tr>)}</tbody></table></div> : <EmptyBlock title="لا أصناف بعد" text="أضف أول صنف ليظهر في قائمة المطعم."/>}</div></>}
  <EntityDialog open={!!category} onClose={() => setCategory(null)} title={category === 'new' ? 'تصنيف جديد' : 'تعديل التصنيف'} fields={[{ key:'name', label:'اسم التصنيف', required:true }]} initial={category === 'new' ? {} : category || {}} testId="category" onSave={async v => { if (category === 'new') await write('/api/admin/categories','POST',{ restaurantId, name:text(v.name).trim() }); else if (category) await write(`/api/admin/categories/${category.id}`,'PATCH',{ name:text(v.name).trim() }); await menu.refetch(); }}/>
  <EntityDialog open={!!product} onClose={() => setProduct(null)} title={product === 'new' ? 'صنف جديد' : 'تعديل الصنف'} fields={productFields} initial={product === 'new' ? { isAvailable:true, categoryId:activeCategories[0]?.id } : product || {}} testId="product" onSave={async v => { if (!v.categoryId || !activeCategories.some(c => c.id === number(v.categoryId))) throw new Error('اختر تصنيفاً متاحاً للصنف أو استعد التصنيف المؤرشف أولاً.'); const body = { restaurantId, name:text(v.name).trim(), categoryId:number(v.categoryId), description:v.description || null, price:number(v.price), stockQuantity:v.stockQuantity === '' ? null : number(v.stockQuantity), imageUrl:v.imageUrl || null, isAvailable:!!v.isAvailable }; if (product === 'new') await write('/api/admin/products','POST',body); else if (product) await write(`/api/admin/products/${product.id}`,'PATCH',body); await menu.refetch(); }}/>
  <ConfirmDialog open={!!restore} onClose={() => setRestore(null)} title="استعادة التصنيف؟" description={`سيصبح ${restore?.name || 'التصنيف'} متاحاً للاختيار عند إضافة الأصناف.`} action="تأكيد الاستعادة" testId="category-restore" onConfirm={async () => { if (restore) { await write(`/api/admin/categories/${restore.id}`,'PATCH',{isAvailable:true}); await menu.refetch(); } }}/>
  <ConfirmDialog open={!!remove} onClose={() => setRemove(null)} title={`أرشفة ${remove?.type === 'category' ? 'التصنيف' : 'الصنف'}؟`} description={`سيُخفى ${remove?.name || 'العنصر'} من القائمة، مع الحفاظ على سجلات الطلبات القديمة.`} action="تأكيد الأرشفة" testId="menu-item" onConfirm={async () => { if (remove) { await write(`/api/admin/${remove.type === 'category' ? 'categories' : 'products'}/${remove.id}`,'DELETE'); await menu.refetch(); } }}/>
  </div>;
}